ssl:
  # Must be true if using SSL!
  enabled: true
wifi:
  # Your WiFi SSID
  ssid: "Your-WiFi-SSID"
      # Your WiFi Password
  passwd: Your-WiFi-Password
mqtt:
  # Your MQTT server
  server: xformer.utilitymonitor.io
  # The port the MQTT server is running on
  port: 8883
  # Your MQTT User
  user: test
  # Your MQTT Password
  password: secure-mqtt-pass
  # A unique ID
  id: unique-id


# Only for the ATM90E36 board
# determines which line to read
# Determines which voltage needs to be set.
XFORMER_MON_LINE='A'

# To be set later:
XFORMER_MON_LINE='A'
