wifi:
  # Your WiFi SSID
  ssid: "Your-WiFi-SSID"
  # Your WiFi Password
  password: "Your-Secret-WiFi-Password"
mqtt:
  # Your MQTT server
  server: your.mqtt-broker.tld
  # The port the MQTT server is running on
  port: 8883
  # Your MQTT User
  user: test
  # Your MQTT Password
  password: secure-mqtt-pass
  # A unique ID, usually the name of the transformer
  id: unique-id